### ISSUE TITLE
Change `parse_line` function api to take &str instead of String

### ISSUE THREAD

**Issue by amanjeev** [ferrous-systems/rust-exercises#19]
## What 

`parse_line` function does not need to take owned string.

## Where

https://github.com/ferrous-systems/rust-exercises/blob/main/exercise-solutions/files-match-result/examples/step_5.rs#L5

```rust
fn parse_line(line: String) -> Option<Url> { // <--- String can be &str
    match Url::parse(&line) {
        Ok(u) => Some(u),
        Err(_e) => None,
    }
}
```

## Fix

Change to `&str`

**Comment by jonathanpallant** [comment]
This has been done
