### ISSUE TITLE
Revisit the use of `trim()` in simple-db

### ISSUE THREAD

**Issue by amanjeev** [ferrous-systems/rust-exercises#24]
I think it came up in a training recently that the trim [usage in the solution for simple-db](https://github.com/ferrous-systems/rust-exercises/blob/main/exercise-solutions/connected-mailbox/simple-db/src/lib.rs#L46) will accodentally trim the whitespace too.

[`trim()` usage is also mentioned in the exercise itself](https://github.com/ferrous-systems/rust-exercises/blob/main/exercise-book/src/simple-db.md?plain=1#L28).

**Comment by jonathanpallant** [comment]
Closed by #25
