### ISSUE TITLE
Add tcp-client (from older repo) to this repo, for Connected mailbox exercise

### ISSUE THREAD

**Issue by amanjeev** [ferrous-systems/rust-exercises#26]
For Connected mailbox exercise, trainees may need a client to connect to their servers. They can use `netcat` or `nc` but we need to provide an alternative. Previous repository of training material has this: https://github.com/ferrous-systems/teaching-material/tree/main/assignments/solutions/tcp-client

**Comment by jonathanpallant** [comment]
We have https://github.com/ferrous-systems/rust-exercises/tree/main/tools/tcp-client ?
